name: notify

on:
  pull_request:
    types: [opened]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Send message for pull request opened
        if: github.event_name == 'pull_request'
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "Blog Pessoal - Bot"
          message: |
            🎉 Novo Pull request aberto!
            **${{ github.event.pull_request.title }}**
            ${{ github.event.pull_request.body }}
            [Repositório](${{
              github.event.repository.html_url
            }})
            [Pull Request](${{
              github.event.pull_request.html_url
            }})

      - name: Send message for merge to master
        if: github.event_name == 'push'
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "Blog Pessoal - Bot"
          message: |
            🚀 Pull request mesclado na master!
            **${{ github.event.head_commit.message }}**
            Autor: ${{ github.event.head_commit.author.name }}
            [Repositório](${{
              github.event.repository.html_url
            }})
            [Pull Request](${{
              github.event.head_commit.url
            }})
